version: "3.0"
services:
  redis:
    image: "redis:alpine"
    networks:
      - data_sharing
  db:
    image: mongo:5.0.29
    networks:
      - data_sharing
  wow-realm-status-notifier:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 3000:3000
      depends_on: 
        - redis
        - db
      environment:
      - MONGODB_HOST=db
      env_file:
        - .env
networks:
  data_sharing:
    driver: bridge