name: build-api
    
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test Code
        run: go test ./..

      - name: Docker build
        run: docker build . -t wow-realm-status-notifier