name: build-api
defaults:
  run:
    working-directory: api
    
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build . -t personal-pass-manager